---
# dataverse/tasks/db.postgres.yml

- name: install postgres
  debug:
    msg: '##### POSTGRES #####'

- name: ansible postgres module wants python-psycopg2 on debian and RedHat 7
  package:
    name: python-psycopg2
    state: latest
  when: (ansible_os_family == "RedHat" and
        ansible_distribution_major_version == "7") or
        (ansible_os_family == "Debian" and
        ansible_distribution_major_version == "10")

- name: ansible postgres module wants python3-psycopg2
  package:
    name: python3-psycopg2
    state: latest
  when: (ansible_os_family == "RedHat" and
        ansible_distribution_major_version == "8") or
        (ansible_os_family == "Debian" and
        ansible_distribution_major_version == "11")

- name: import RPM-GPG-KEY-PGDG
  rpm_key:
    state: present
    key: https://download.postgresql.org/pub/repos/yum/RPM-GPG-KEY-PGDG
  when: ansible_os_family == "RedHat"

- name: install postgres repo RPM
  yum:
    name: 'https://download.postgresql.org/pub/repos/yum/reporpms/EL-{{ ansible_distribution_major_version }}-x86_64/pgdg-redhat-repo-latest.noarch.rpm'
    state: present
  when: ansible_os_family == "RedHat"

- name: import gpg-key
  apt_key:
    state: present
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
  when: ansible_os_family == "Debian"

- name: install postgres repo deb
  apt_repository:
    repo: deb http://apt.postgresql.org/pub/repos/apt/ focal-pgdg main
    state: present
  when: ansible_os_family == "Debian"  

- name: "RHEL/Rocky8: disable PostgreSQL proper in the OS"
  shell: 'dnf -qy module disable postgresql'
  when: ansible_os_family == "RedHat" and
        ansible_distribution_major_version == "8"

- name: postgres uses differing version syntax in a few commands/packages
  set_fact:
    dataverse_pg_version_short: "{{ db.postgres.version | regex_replace('\\.','') }}"

- name: install postgres server on RedHat / Rocky
  yum:
   name: 'postgresql{{ dataverse_pg_version_short }}-server'
   state: latest
  when: ansible_os_family == "RedHat" and
        db.use_rds == false

- name: install postgres server on Debian
  apt:
   name: 'postgresql-{{ dataverse_pg_version_short }}'
   state: latest
  when: ansible_os_family == "Debian" and
        db.use_rds == false

- name: install postgres client on RedHat / Rocky for RDS
  yum:
    name: 'postgresql{{ dataverse_pg_version_short }}'
    state: latest
  when: ansible_os_family == "RedHat" and
        db.use_rds == true

- name: install postgres client on Debian
  apt:
    name: 'postgresql-client-{{ dataverse_pg_version_short }}'
    state: latest
  when: ansible_os_family == "Debian" and
        db.use_rds == true

- include: postgresql-init.yml
  when: db.use_rds == false

- name: install pg_hba.conf on RHEL/Rocky
  copy:
    src: pg_hba.conf
    dest: '/var/lib/pgsql/{{ db.postgres.version }}/data'
    owner: postgres
    group: postgres
    mode: 0644
  when: ansible_os_family == "RedHat" and
        db.use_rds == false
  notify: enable and restart postgres

- name: install pg_hba.conf on Debian
  copy:
    src: pg_hba.conf
    dest: '/etc/postgresql/{{ db.postgres.version }}/main'
    owner: postgres
    group: postgres
    mode: 0644
  when: ansible_os_family == "Debian" and
        db.use_rds == false
  notify: enable and restart postgres

- name: log_lock_waits when told
  lineinfile:
    path: '/var/lib/pgsql/{{ db.postgres.version }}/data/postgresql.conf'
    regexp: '^#log_lock_waits'
    line: 'log_lock_waits = on'
  when: db.postgres.log_lock_waits == true and
        db.use_rds == false and
        ansible_os_family == "RedHat"
  notify: enable and restart postgres

- name: log_lock_waits when told
  lineinfile:
    path: '/etc/postgresql/{{ db.postgres.version }}/main/postgresql.conf'
    regexp: '^#log_lock_waits'
    line: 'log_lock_waits = on'
  when:
   - ansible_os_family == "Debian"
   - db.postgres.log_lock_waits
   - not db.use_rds
  notify: enable and restart postgres

- meta: flush_handlers

- name: dataverse python installer wants to be a postgres admin
  postgresql_user:
    name: postgres
    password: '{{ db.postgres.adminpass }}'
  when: db.use_rds == false

- name: create dataverse postgres database
  postgresql_db:
    name: '{{ db.postgres.name }}'
  when: db.use_rds == false

- name: create dataverse postgres user, set permissions
  postgresql_user:
    db: '{{ db.postgres.name }}'
    name: '{{ db.postgres.user }}'
    password: '{{ db.postgres.pass }}'
    role_attr_flags: 'NOSUPERUSER,CREATEDB,CREATEROLE,INHERIT,LOGIN'
  when: db.use_rds == false

- include: postgres_sequential_identifiers.yml
  when: dataverse.api.test_suite == true
